sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - git clone --depth=50 --branch=web-apps git://github.com/jburel/omero-test-infra .omero

script:
  - APP_BUILD=false .omero/app-docker
  - SET_UP=false DIR_SCRIPTS=omero_figure/scripts/omero .omero/scripts-docker
